name: Run Selenium Test

on:
  workflow_dispatch:  # это позволяет запускать вручную с кнопки в GitHub

jobs:
  run:
    runs-on: self-hosted # GitHub будет запускать код на сервере с Ubuntu

    steps:
    - name: Скачать код из репозитория
      uses: actions/checkout@v3

    - name: Установить Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Установить библиотеки Python
      run: pip install selenium


    - name: Установить библиотеки opencv
      run: pip install opencv-python

    - name: Запустить твой скрипт
      working-directory: valor
      run: python test-slots.py

#