name: Run Selenium Test

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted

    steps:
    - name: Проверить версию Python
      run: python --version

    - name: Установить зависимости
      run: pip install selenium opencv-python pyautogui webdriver-manager faker requests

    - name: Запустить скрипт
      working-directory: valor
      run: python test-slots.py

    - name: Push Report to repo
<<<<<<< HEAD
=======
      working-directory: valor
      shell: powershell
>>>>>>> f081606 (РђРІС‚РѕРѕС‚С‡РµС‚ РїРѕСЃР»Рµ С‚РµСЃС‚Р°)
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

<<<<<<< HEAD
        git add .

        try {
          git commit -m "Автоотчет после теста"
        } catch {
          Write-Host "No changes to commit"
        }

        try {
          git pull --rebase origin main
        } catch {
          Write-Host "Rebase failed or not needed"
        }

        git push origin main
=======
        git pull --rebase origin main
        
        git add .

        try {
        git commit -m "Автоотчет после теста" --no-edit
        } catch {
        Write-Host "No changes to commit"
        }

        git push origin main


>>>>>>> f081606 (РђРІС‚РѕРѕС‚С‡РµС‚ РїРѕСЃР»Рµ С‚РµСЃС‚Р°)
