name: Run Selenium Test

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - name: Скачать код из репозитория
      uses: actions/checkout@v3

    - name: Установить Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Установить библиотеки Python
      run: |
        pip install selenium
        pip install opencv-python  # Добавляем установку OpenCV

    - name: Запустить твой скрипт
      working-directory: valor
      run: python test-slots.py
