name: Run Selenium Test

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted

    steps:
    - name: Проверить версию Python
      run: python --version

    - name: Установить зависимости
      run: pip install selenium opencv-python pyautogui webdriver-manager faker requests

    - name: Очистить папку docs перед запуском
      shell: powershell
      run: |
        if (Test-Path "docs") {
          Remove-Item -Path "docs\*" -Recurse -Force
        }

    - name: Запустить скрипт
      working-directory: valor
      run: python test-slots.py

    - name: Push Report to repo
      working-directory: valor
      shell: powershell
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

        git add -A

        try {
          git commit -m "Автоотчет после теста"
        } catch {
          Write-Host "No changes to commit"
        }

        try {
          git pull --rebase origin main
        } catch {
          Write-Host "Rebase failed or not needed"
        }

        git push origin main
