name: Run Selenium Test

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted

    steps:
    - name: Проверить версию Python
      run: python --version

    - name: Запустить твой скрипт
      working-directory: valor
      run: python test-slots.py
