name: Run Selenium Test

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: self-hosted

    steps:
    - name: Проверить версию Python
      run: python --version

    - name: Установить зависимости
      run: pip install selenium opencv-python pyautogui webdriver-manager faker requests

    - name: Запустить скрипт
      working-directory: valor
      run: python test-slots.py

    - name: Push Report to repo
      working-directory: valor
      run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin main
          git reset --soft origin/main
          git add .
          git commit -m "Автоотчет после теста" || echo "No changes to commit"
          git pull --rebase origin main || echo "Rebase failed or no changes"
          git push origin main
