name: Run Selenium Test

on:
  workflow_dispatch:  # Позволяет запускать workflow вручную через GitHub UI

jobs:
  run:
    runs-on: self-hosted  # Запуск на вашем локальном сервере (self-hosted runner)

    steps:
    - name: Скачать код из репозитория
      uses: actions/checkout@v3  # Клонирование репозитория

    - name: Установить зависимости
      run: |
        python -m pip install --upgrade pip  # Обновление pip
        python -m pip install -r requirements.txt  # Установка всех зависимостей из requirements.txt

    - name: Проверка Python
      run: |
        where python  # Находит путь к Python
        python --version  # Проверяет версию установленного Python

    - name: Запуск теста
      working-directory: valor  # Переход в директорию с тестами
      run: python test-slots.py  # Запуск теста
